echo "NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION" >> .env
echo "NEXT_PUBLIC_IMGIX_HOSTNAME=$NEXT_PUBLIC_IMGIX_HOSTNAME" >> .env
echo "NEXT_PUBLIC_GITHUB_REPO=$NEXT_PUBLIC_GITHUB_REPO" >> .env
echo "NEXT_PUBLIC_ASSET_PLATFORM=$NEXT_PUBLIC_ASSET_PLATFORM" >> .env
echo "NEXT_PUBLIC_BALANCER_POOL_ID=$NEXT_PUBLIC_BALANCER_POOL_ID" >> .env
echo "NEXT_PUBLIC_INFURA_API_KEY=$NEXT_PUBLIC_INFURA_API_KEY" >> .env
echo "NEXT_PUBLIC_COINGECKO_API_KEY=$NEXT_PUBLIC_COINGECKO_API_KEY" >> .env
echo "NEXT_PUBLIC_NODE_REAL_API_KEY=$NEXT_PUBLIC_NODE_REAL_API_KEY" >> .env
echo "NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID" >> .env
echo "NEXT_PUBLIC_HOTJAR_SITE_ID=$NEXT_PUBLIC_HOTJAR_SITE_ID" >> .env
echo "NEXT_PUBLIC_MULTICALL_CONTRACT=$NEXT_PUBLIC_MULTICALL_CONTRACT" >> .env
echo "NEXT_PUBLIC_STAKING_ADDRESS=$NEXT_PUBLIC_STAKING_ADDRESS" >> .env
echo "NEXT_PUBLIC_VAULT_ADDRESS=$NEXT_PUBLIC_VAULT_ADDRESS" >> .env
echo "NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID" >> .env
echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> .env
echo "IMGIX_HOSTNAME=$IMGIX_HOSTNAME" >> .env

echo "NEXT_PUBLIC_DEFAULT_CHAIN_ID=$DEFAULT_CHAIN_ID" >> .env

echo "NEXT_PUBLIC_AWS_BRANCH=$AWS_BRANCH" >> .env
echo "NEXT_PUBLIC_AWS_JOB_ID=$AWS_JOB_ID" >> .env
echo "NEXT_PUBLIC_AWS_JOB_ID=$AWS_JOB_ID" >> .env
echo "NEXT_PUBLIC_AWS_COMMIT_ID=$AWS_COMMIT_ID" >> .env

echo "NEXT_PUBLIC_GOOGLE_TAG_MANAGER=$NEXT_PUBLIC_GOOGLE_TAG_MANAGER" >> .env

echo "NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID" >> .env